// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wceotkgwnotpaaykibcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjZW90a2d3bm90cGFheWtpYmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzU3MjAsImV4cCI6MjA2MTE1MTcyMH0.L_jE9gNsHn4MUypUeArX5LDL-_fBHsuZclxeKcwrWRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);